import assert from 'node:assert/strict';
import { createCipheriv, createDecipheriv, hkdfSync } from 'node:crypto';
import { readFileSync } from 'node:fs';

const vector = JSON.parse(readFileSync(
  new URL('../protocol/vectors/v1.json', import.meta.url),
  'utf8',
));

const decode = (value) => Buffer.from(value, 'base64url');
const encode = (value) => Buffer.from(value).toString('base64url');

function encryptGcm(plaintext, key, iv, aad) {
  const cipher = createCipheriv('aes-256-gcm', key, iv, { authTagLength: 16 });
  cipher.setAAD(aad);
  return Buffer.concat([cipher.update(plaintext), cipher.final(), cipher.getAuthTag()]);
}

function decryptGcm(ciphertextAndTag, key, iv, aad) {
  const tagOffset = ciphertextAndTag.length - 16;
  const ciphertext = ciphertextAndTag.subarray(0, tagOffset);
  const tag = ciphertextAndTag.subarray(tagOffset);
  const decipher = createDecipheriv('aes-256-gcm', key, iv, { authTagLength: 16 });
  decipher.setAAD(aad);
  decipher.setAuthTag(tag);
  return Buffer.concat([decipher.update(ciphertext), decipher.final()]);
}

const { envelope } = vector;
const canonicalAad = JSON.stringify({
  version: envelope.version,
  algorithm: envelope.algorithm,
  id: envelope.id,
  ttlSeconds: envelope.ttlSeconds,
  signature: envelope.signature,
});
assert.equal(canonicalAad, vector.aad, 'canonical AAD drifted');

const aad = Buffer.from(vector.aad, 'utf8');
const kek = Buffer.from(hkdfSync(
  'sha256',
  decode(vector.fragmentSecret),
  decode(envelope.hkdfSalt),
  Buffer.from(`snow-whisper:v1:kek:${envelope.id}`, 'utf8'),
  32,
));
assert.equal(encode(kek), vector.derivedKek, 'HKDF output drifted');

const contentKey = decode(vector.contentKey);
assert.equal(
  encode(encryptGcm(contentKey, kek, decode(envelope.wrapIv), aad)),
  envelope.wrappedKey,
  'wrapped content key drifted',
);
assert.equal(
  encode(encryptGcm(Buffer.from(vector.plaintext, 'utf8'), contentKey, decode(envelope.contentIv), aad)),
  envelope.ciphertext,
  'content ciphertext drifted',
);

const decryptedKey = decryptGcm(decode(envelope.wrappedKey), kek, decode(envelope.wrapIv), aad);
const plaintext = decryptGcm(decode(envelope.ciphertext), decryptedKey, decode(envelope.contentIv), aad);
assert.deepEqual(decryptedKey, contentKey);
assert.equal(plaintext.toString('utf8'), vector.plaintext);

console.log('protocol v1 vector regenerated byte-for-byte and decrypted with node:crypto');
